version: "1"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: wedev_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - project

  mysql:
    image: mysql:latest
    container_name: wedev_mysql
    restart: always
    tty: true
    ports:
     - "3307:3307"
    environment:
      MYSQL_DATABASE: default
      MYSQL_ROOT_PASSWORD: admin
      # MYSQL_USER: root
      # MYSQL_PASSWORD:
      # MYSQL_ROOT_PASSWORD:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - project

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wedev_php
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - project

networks:
  project:
